name: pharma_fix
description: A new Flutter project for Pharmacy POS and Inventory.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Database (Offline-First)
  drift: ^2.14.1
  sqlite3_flutter_libs: ^0.5.18
  path_provider: ^2.1.2
  path: ^1.8.3
  
  # State Management
  flutter_bloc: ^8.1.3
  
  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2
  
  # Logic & Utils
  decimal: ^3.0.1
  uuid: ^4.3.3
  dio: ^5.4.1
  go_router: ^13.2.0
  intl: ^0.19.0
  mobile_scanner: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  
  # Code Generation
  drift_dev: ^2.14.1
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
