import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import 'tables/tables.dart';
import 'daos/batch_dao.dart';
import 'daos/invoice_dao.dart';

part 'app_database.g.dart'; // Generated by build_runner

@DriftDatabase(
  tables: [
    Products,
    Batches,
    Customers,
    Invoices,
    InvoiceItems,
    StockMovements,
    Debts,
  ],
  daos: [BatchDao, InvoiceDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 1;
}

// Opens SQLite database from the device's document directory (Offline-First)
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'pharmafix.db'));
    return NativeDatabase.createInBackground(file);
  });
}
