import 'dart:io';
import 'package:drift/drift.dart';
import 'package:drift/native.dart';
import 'package:path_provider/path_provider.dart';
import 'package:path/path.dart' as p;

import 'tables/tables.dart';
import 'daos/batch_dao.dart';
import 'daos/invoice_dao.dart';

part 'app_database.g.dart'; // Generated by build_runner

@DriftDatabase(
  tables: [
    Products,
    Batches,
    Customers,
    Invoices,
    InvoiceItems,
    StockMovements,
    Debts,
  ],
  daos: [BatchDao, InvoiceDao],
)
class AppDatabase extends _$AppDatabase {
  AppDatabase() : super(_openConnection());

  @override
  int get schemaVersion => 2;

  @override
  MigrationStrategy get migration => MigrationStrategy(
    onUpgrade: (m, from, to) async {
      if (from < 2) {
        // Since we are in early dev, we'll just drop and recreate everything
        // In production, we would use m.addColumn(invoiceItems, invoiceItems.suggestedPrice)
        for (final table in allTables) {
          await m.deleteTable(table.actualTableName);
          await m.createTable(table);
        }
      }
    },
    beforeOpen: (details) async {
      // Logic for foreign keys can go here
      await customStatement('PRAGMA foreign_keys = ON');
    },
  );
}

// Opens SQLite database from the device's document directory (Offline-First)
LazyDatabase _openConnection() {
  return LazyDatabase(() async {
    final dbFolder = await getApplicationDocumentsDirectory();
    final file = File(p.join(dbFolder.path, 'pharmafix.db'));
    return NativeDatabase.createInBackground(file);
  });
}
